server:
  port: 9004

spring:
  application:
    name: index12306-pay${unique-name:}-service
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.150.100:8848
      password: nacos
      username: nacos
    sentinel:
      transport:
        dashboard: 192.168.150.100:8686
        port: 8719
  data:
    redis:
      host: 192.168.150.100
      port: 6379


rocketmq:
  name-server: 192.168.150.100:9876
  producer:
    group: index12306_pay-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

pay:
  alipay:
    app-id: 2021000147645264
    charset: UTF8
    format: json
    notify-url: http://1603b8b94d7f6e56.natapp.cc/api/pay-service/callback/alipay
    server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    merchant-private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDE+skF0r5Se1gpZVXHH+RD/Bnck3zHlQiqawiwwBiSOubFt8tP7+ONPctlscAjYRdSTZt6D6RTqc/k1uEjrLj24XF0gGjMVSLPxcRLielal4pEQyc3dzjOByw3mYuPwC2oRhh2V+e4Q/c4ax+NKlVV9G2WmJkBX+zoC8/Dcb4Z4KWl8JdwtUqBnDrfhilA1z7mkblainZj0XXYfvG3J/rupLHKd6efTY3gAsjdwdAzXo1OcGQAhBPA+B4wzTDs0MSzl5ZHq+4+nwC3bGJfoxV85f+Ijn6tUyVEvWuDEVlNIyLnQKZfpPgu61DnD/A2d/ynoqZo9+5evDqG2xF0aN8PAgMBAAECggEBAK5Jg4J+hF2wu0HtYqdMZYltz2gmq3pgOImpKMhTP6prKXN5+w+gnwOC0KwLSYlESAFPn6ixnGFWWBcPtab+Fa6DrQI69/8LuUCDqPp5bRr2CKX7kQB3obBSEmKjniO0E/HXC5/yiZm1sVGfHwylj1n9atWb8Y2Q1ao/gTZaNqznVJzm3il2lPVQK8o34QAvHOkloxDa/RBRmzWLM9nOAMqtTszel9Lplfn1LqCByUhU9vbudDKdIr3t0p6HE5N+6cEdJvlyw2MvpHQVBJZQD5hdvOEroxbDezBq5u4XXwAefwPJrCwa5lAN3/ON2h5rUcegikaWbvLAZmNhtycs7CECgYEA82eB5mUIM4dSSOCv2A7WVNaunqN+zcQ3swqH8NqyZeBqnk9LnmqMlG2GpyIWGQkV+wYCwfyBmt9rJKV+8Sxc7wFgeGFFkDwKOEaBIBZpysmfDtkEKhwRr8RzYYI3r+RxWlc92fMawXdpGTwryj75XpCLxe7XSLxiBTFq9RWX418CgYEAzyxEkeJ1+mj8CqVYuXagXxVj00J0jwZxx0ImutaY3NCa2baCZjgJXlX5ONiJhiAP6krFSa4TDpTmE29w3opGyiR+C1eOazppD4Cte/19YIHntlTeBS3T7s+b9U+vBfwbNTaoOHoNoHE3NdQ/7//QhQudKojTXAVzEB0Ztg7q0lECgYArM4Pq0KPUAYCpTrfnMTr5c+EqZvpqqxj3vjbCmQ5w5pQF5S0WwPKSpZ3wrCwf5WzxUO/MXnTieCUcLAOL6sPT5/qnYxxlrUJjGqBwgYnlZEPG7t2+W50IBWY1OFeJ8JHt5u4jcPKexALzZ6qeCu9XyXAFgY7Uahs7sLm7Jkn/IQKBgQDB0ShVUwgMvSsOyqG24MQoMFqzyfhB1kWbpMeXBCz+aCp2g8h62PHqz4PZKrt+P4CkME9iHvi1K5gTlq6Bg9u2QW2qLr+OkZa4ainjVcN2BhJBAiSzs6wSPygo1+NmNfU+U2QNciJNd52vPmKSpUDvN25R3K/f5zk+Wfsz18DYAQKBgQC1Dra0h9sf0wDm6nJP82YO5xNUQzAb5c54BEI3a6viZvJ9CCr5fiPw+RGQiE4dJbYYGeg9I0lO7Ipl5fq+rIhE5GK+kuaVNHMuO7NaEbgmx5qWdEnjO5JuLIqTYuQJXZ6sCGlhGwYG8mOAcqUoH0TBv8cF5uWmZDygGQbam3qp5A==
    sign-type: RSA2
    private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDE+skF0r5Se1gpZVXHH+RD/Bnck3zHlQiqawiwwBiSOubFt8tP7+ONPctlscAjYRdSTZt6D6RTqc/k1uEjrLj24XF0gGjMVSLPxcRLielal4pEQyc3dzjOByw3mYuPwC2oRhh2V+e4Q/c4ax+NKlVV9G2WmJkBX+zoC8/Dcb4Z4KWl8JdwtUqBnDrfhilA1z7mkblainZj0XXYfvG3J/rupLHKd6efTY3gAsjdwdAzXo1OcGQAhBPA+B4wzTDs0MSzl5ZHq+4+nwC3bGJfoxV85f+Ijn6tUyVEvWuDEVlNIyLnQKZfpPgu61DnD/A2d/ynoqZo9+5evDqG2xF0aN8PAgMBAAECggEBAK5Jg4J+hF2wu0HtYqdMZYltz2gmq3pgOImpKMhTP6prKXN5+w+gnwOC0KwLSYlESAFPn6ixnGFWWBcPtab+Fa6DrQI69/8LuUCDqPp5bRr2CKX7kQB3obBSEmKjniO0E/HXC5/yiZm1sVGfHwylj1n9atWb8Y2Q1ao/gTZaNqznVJzm3il2lPVQK8o34QAvHOkloxDa/RBRmzWLM9nOAMqtTszel9Lplfn1LqCByUhU9vbudDKdIr3t0p6HE5N+6cEdJvlyw2MvpHQVBJZQD5hdvOEroxbDezBq5u4XXwAefwPJrCwa5lAN3/ON2h5rUcegikaWbvLAZmNhtycs7CECgYEA82eB5mUIM4dSSOCv2A7WVNaunqN+zcQ3swqH8NqyZeBqnk9LnmqMlG2GpyIWGQkV+wYCwfyBmt9rJKV+8Sxc7wFgeGFFkDwKOEaBIBZpysmfDtkEKhwRr8RzYYI3r+RxWlc92fMawXdpGTwryj75XpCLxe7XSLxiBTFq9RWX418CgYEAzyxEkeJ1+mj8CqVYuXagXxVj00J0jwZxx0ImutaY3NCa2baCZjgJXlX5ONiJhiAP6krFSa4TDpTmE29w3opGyiR+C1eOazppD4Cte/19YIHntlTeBS3T7s+b9U+vBfwbNTaoOHoNoHE3NdQ/7//QhQudKojTXAVzEB0Ztg7q0lECgYArM4Pq0KPUAYCpTrfnMTr5c+EqZvpqqxj3vjbCmQ5w5pQF5S0WwPKSpZ3wrCwf5WzxUO/MXnTieCUcLAOL6sPT5/qnYxxlrUJjGqBwgYnlZEPG7t2+W50IBWY1OFeJ8JHt5u4jcPKexALzZ6qeCu9XyXAFgY7Uahs7sLm7Jkn/IQKBgQDB0ShVUwgMvSsOyqG24MQoMFqzyfhB1kWbpMeXBCz+aCp2g8h62PHqz4PZKrt+P4CkME9iHvi1K5gTlq6Bg9u2QW2qLr+OkZa4ainjVcN2BhJBAiSzs6wSPygo1+NmNfU+U2QNciJNd52vPmKSpUDvN25R3K/f5zk+Wfsz18DYAQKBgQC1Dra0h9sf0wDm6nJP82YO5xNUQzAb5c54BEI3a6viZvJ9CCr5fiPw+RGQiE4dJbYYGeg9I0lO7Ipl5fq+rIhE5GK+kuaVNHMuO7NaEbgmx5qWdEnjO5JuLIqTYuQJXZ6sCGlhGwYG8mOAcqUoH0TBv8cF5uWmZDygGQbam3qp5A==
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxPrJBdK+UntYKWVVxx/kQ/wZ3JN8x5UIqmsIsMAYkjrmxbfLT+/jjT3LZbHAI2EXUk2beg+kU6nP5NbhI6y49uFxdIBozFUiz8XES4npWpeKREMnN3c4zgcsN5mLj8AtqEYYdlfnuEP3OGsfjSpVVfRtlpiZAV/s6AvPw3G+GeClpfCXcLVKgZw634YpQNc+5pG5Wop2Y9F12H7xtyf67qSxynenn02N4ALI3cHQM16NTnBkAIQTwPgeMM0w7NDEs5eWR6vuPp8At2xiX6MVfOX/iI5+rVMlRL1rgxFZTSMi50CmX6T4LutQ5w/wNnf8p6KmaPfuXrw6htsRdGjfDwIDAQAB

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper-locations: classpath:mapper/*.xml

framework:
  fastjson:
    safe-mode: true
  cache:
    redis:
      value-timeout: 16
      value-time-unit: days

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
